---
title: "Getting Ready for RDojo"
author: "Joe Hoover"
date: '`r Sys.Date()`'
output: 
  md_document:
    variant: markdown_github
---

```{r, echo=F}
knitr::opts_knit$set(base.dir = "~/offline_research/git_repos/usc-rdojo.github.io/", base.url = "/")
knitr::opts_chunk$set(fig.path = "images/R/")


# render(input = "_source/2017-05-17-hello.Rmd", output_dir = "_posts", output_format = md_document(preserve_yaml = TRUE))
```

One of the primary goals of RDojo is providing value to R users with different degrees of expertise. So, you **do not** need to be an expert (or anything close) to participate in RDojo -- if you've never used R in your life, that's fine!

However, because we want to be useful to many different levels of users, we do ask that you come prepared with the kind of basic knowledge that you can get with a little bit of exploration and elbow grease. 

Here's a list of things that you might want to do/be familiar with:

* *Install R and RStudio.* RStudio is a user-friendly program that streamlines working with the statistical computing platform R. Most R users (but certainly not all) use RStudio and that's what we will be doing at RDojo. To install RStudio, you first have to install R. There are ample guides for installing both programs for any given operating system, so if you run into trouble Google can probably help you out. 

* *Install Latex* One of the features of RStudio that RDojo will rely on will be the program's capacity for document generation. Using a package --an RStudio program-- called `knitr`, you can dynamically generate PDF's, html files, and word documents that incorporate formatted text, code, and computational and graphical output. Once you get comfortable with this framework, you can actually write entire manuscripts in RStudio and you'll never have to copy and paste a single number from a statistical test. To use `knitr` you need to install a formatting language called latex. You can do that here <a href='https://www.latex-project.org/get/'>. You can read more about knitr and generating formatted documents in RStudio here <a href ='https://support.rstudio.com/hc/en-us/articles/200552056-Using-Sweave-and-knitr'>

*NOTE:* **Installing latex requires downloading a large file; you might want to do this overnight.**


* *Spend some time getting comfortable with R & RStudio* There are many good resources for learning R/RStudio. While learning about R/Rstudio is the entire purpose of RDojo, it's useful for everyone to have some degree of familiarity with the basics. You can find a list of excellent introductory resources here <a href='https://www.rstudio.com/online-learning/#R'> 


